

model V09GA07
  extends Pharmacokinetic.Models.PK_1C_enteral(
    weight         = 70,
    F              = 1,
    Cl             = 0.006333333333333333,
    adminDuration  = 600,
    adminMass      = 0.0005,
    adminCount     = 1,
    Vd             = 0.0043,
    Cmin           = 0.001,
    Cmax           = 0.01,
    Ctox_peak      = 0.02,
    Ctox_trough    = 0.01,
    ka             = 0.0,
    Tlag           = 0
  );

  annotation(Documentation(
    info ="<html><body><p>Technetium (99mTc) apcitide is a radiopharmaceutical agent used for imaging to detect deep vein thrombosis (DVT) in the lower extremities. It binds selectively to the glycoprotein IIb/IIIa receptors present on activated platelets at sites of thrombus formation. The drug is approved for clinical use as a diagnostic tool in nuclear medicine.</p><h4>Pharmacokinetics</h4><p>Pharmacokinetic estimate in adults based on available product labeling and secondary sources; parameters are for healthy volunteers.</p><h4>References</h4><ol><li>M P Bernarducci,\"Pathophysiologic mapping\" of venous thromboembolism: opportunities for radiolabeled peptides.,The quarterly journal of nuclear medicine : official publication of the Italian Association of Nuclear Medicine (AIMN) [and] the International Association of Radiopharmacology (IAR),2003<a href='https://pubmed.ncbi.nlm.nih.gov/14973421/'>https://pubmed.ncbi.nlm.nih.gov/14973421/</a></li><li>Paul M Sherman, Robert S Bridwell,Focal accumulation of a radiopharmaceutical in the liver on technetium-99m gated blood pool and Apcitide scintigraphy leading to the diagnosis of superior vena cava obstruction.,Military medicine,2002<a href='https://pubmed.ncbi.nlm.nih.gov/11799821/'>https://pubmed.ncbi.nlm.nih.gov/11799821/</a></li></ol></body></html>",
    revisions = "<html><body><ul><li>06/2025 model generated by LLM gpt-4.1, references by scholarly and scripts created by Tomas Kulhanek</li></ul></body></html>"
  ));
end V09GA07;
