

model A08AA07
  extends Pharmacokinetic.Models.PK_1C_enteral(
    weight         = 70,
    F              = 0.82,
    Cl             = 2.0166666666666666,
    adminDuration  = 600,
    adminMass      = 0.05,
    adminCount     = 1,
    Vd             = 0.0015,
    Cmin           = 0.001,
    Cmax           = 0.01,
    Ctox_peak      = 0.02,
    Ctox_trough    = 0.01,
    ka             = 0.007,
    Tlag           = 600
  );

  annotation(Documentation(
    info ="<html><body><p>Cathine (norpseudoephedrine) is a naturally occurring stimulant found in the khat plant (Catha edulis). It is a central nervous system stimulant similar to amphetamine but less potent. Historically, cathine was used as an appetite suppressant and for its mild stimulant properties. Currently, it is a controlled substance in many countries, and it is not an approved pharmaceutical medication for any modern medical use.</p><h4>Pharmacokinetics</h4><p>PK parameters are based on published human studies in healthy adult volunteers (both sexes), following single oral dose administration.</p><h4>References</h4><ol><li>Stefan W Toennes, Sebastian Harder, Markus Schramm, Constanze Niess, Gerold F Kauert,Pharmacokinetics of cathinone, cathine and norephedrine after the chewing of khat leaves.,British journal of clinical pharmacology,2003<a href='https://pubmed.ncbi.nlm.nih.gov/12848785/'>https://pubmed.ncbi.nlm.nih.gov/12848785/</a></li><li>Nilesh B Patel,\"Natural Amphetamine\" Khat: A Cultural Tradition or a Drug of Abuse?,International review of neurobiology,2015<a href='https://pubmed.ncbi.nlm.nih.gov/26070760/'>https://pubmed.ncbi.nlm.nih.gov/26070760/</a></li></ol></body></html>",
    revisions = "<html><body><ul><li>06/2025 model generated by LLM gpt-4.1, references by scholarly and scripts created by Tomas Kulhanek</li></ul></body></html>"
  ));
end A08AA07;
